name: Build Windows and MacOS Binary

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Build EXE
        run: pyinstaller -F --icon=logo.ico EpisodeReName.py
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EpisodeReName-Windows
          path: dist/EpisodeReName.exe

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Build macOS App
        run: |
          pyinstaller -F --icon=logo.icns EpisodeReName.py
          chmod +x dist/EpisodeReName
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EpisodeReName-macOS
          path: dist/EpisodeReName

  release:
    name: Create Release
    needs: [build-windows, build-macos]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: EpisodeReName-*
          merge-multiple: true
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            EpisodeReName.exe
            EpisodeReName
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}